google_Url = https://www.google.com
wikipedia_Url = https://www.wikipedia.org
SearchXpath = //input[@id = 'searchInput']
searchButtonXpath = //button[@type = 'submit']
SearchInput_in_articlePage = //input[@aria-label = 'Search Wikipedia'  and @title='Search Wikipedia [alt-f]']
SearchButton_in_articlePage = //form[@id='searchform']//button[contains(@class,'cdx-search-input__end-button')]
articletitle_Xpath = //span[@class = 'mw-page-title-main']/parent::span/parent::h1